---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Update DNS
      route53:
        state: present
        overwrite: true
        zone: "{{ zone }}"
        private_zone: true
        record: "{{ hostname }}.{{ zone }}"
        type: A
        ttl: 300
        value: "{{ ansible_default_ipv4.address }}"

    - name: Ensure cron is present to update on reboot
      cron:
        name: "update-dns"
        state: present
        special_time: reboot
        user: root
        job: |
          /usr/bin/ansible-pulll -U https://github.com/fullmetalgeo/ansible-playbooks --extra-vars "hostname={{ hostname }} zone={{ zone }}" update-internal-dns.yml >> /var/log/ansible-pull.log
      become: yes
