---
- hosts: localhost
  connection: local
  gather_facts: true

  tasks:
    - name: Update DNS
      route53:
        state: present
        zone: "{{ zone }}"
        private_zone: true
        record: "{{ hostname }}.{{ zone }}"
        type: A
        ttl: 300
        value: "{{ ansible_default_ipv4.address }}"

